In [10]:
import numpy as np
#1.50-100 хүртэл тоон утга бүхий нэг хэмжээст массив (вектор) үүсгэ.
data1 = np.arange(50, 101)
print(data1)

[ 50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85
  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100]


In [32]:
#2.Арван ширхэг 1, арван ширхэг 0, арван ширхэг 6 тоо бүхий нэг хэмжээст массивууд (вектор) үүсгэ.
data2 = np.zeros(10)
data2_1 = np.ones(10)
data2_2 = np.repeat(6, 10)

data2_3 = np.concatenate([data2, data2_1, data2_2])
print(data2_3)



[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 6. 6. 6. 6.
 6. 6. 6. 6. 6. 6.]


In [56]:
#3.20-32 хүртэл тоон утга бүхий 3x4 хэмжээтэй массив үүсгэ.


data3 = np.arange(20,32)
a = np.reshape(data3, (3, 4), "C")
print(a)




[[20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [57]:
#4. Диагональ нь 1-ийн тоо, бусад нь 0 байх 3x3 хэмжээтэй массив үүсгэ.
data4 = np.diag([1,1,1])
print(data4)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [60]:
#5. Диагональ нь 1-5 хүртэл тоо, бусад нь 0 байх 5х5 хэмжээтэй массив үүсгэ.
data5 = np.diag([1,2,3,4,5])
print(data5)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [70]:
#6. Хоёр хэмжээст массив үүсгэж нийт элементүүдийн нийлбэр, багана, мөрийн нийлбэрүүдийг хэвлэ.
data6_1 = [1,2,3,4,5,6]
data6_2 = [7,8,9,10,11,12]

data_array = np.array([data6_1, data6_2])
print(data_array)
print(np.sum(data_array))
print(np.sum(data_array, axis = 0))
print(np.sum(data_array, axis = 1))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
78
[ 8 10 12 14 16 18]
[21 57]


In [73]:
#7. Спортын сайтуудын мэдээллийг ашиглан хөл бөмбөгийн спортын дурын 10 тоглогчийн 
#сүүлийн арван жилийн цалин, нийт тоглолт, оруулсан гоалуудын талаар мэдээллийг цуглуулж тус бүрээр массив үүсгэ.
#Үүсгэсэн массив тус бүрийн багана болон мөрүүдийн нийлбэрийг хэвлэ.

#Salaries
KobeBryant_Salary = [15946875,17718750,19490625,21262500,23034375,24806250,25244493,27849149,30453805,23500000]
JoeJohnson_Salary = [12000000,12744189,13488377,14232567,14976754,16324500,18038573,19752645,21466718,23180790]
LeBronJames_Salary = [4621800,5828090,13041250,14410581,15779912,14500000,16022500,17545000,19067500,20644400]
CarmeloAnthony_Salary = [3713640,4694041,13041250,14410581,15779912,17149243,18518574,19450000,22407474,22458000]
DwightHoward_Salary = [4493160,4806720,6061274,13758000,15202590,16647180,18091770,19536360,20513178,21436271]
ChrisBosh_Salary = [3348000,4235220,12455000,14410581,15779912,14500000,16022500,17545000,19067500,20644400]
ChrisPaul_Salary = [3144240,3380160,3615960,4574189,13520500,14940153,16359805,17779458,18668431,20068563]
KevinDurant_Salary = [0,0,4171200,4484040,4796880,6053663,15506632,16669630,17832627,18995624]
DerrickRose_Salary = [0,0,0,4822800,5184480,5546160,6993708,16402500,17632688,18862875]
DwayneWade_Salary = [3031920,3841443,13041250,14410581,15779912,14200000,15691000,17182000,18673000,15000000]

#Matrix
Salary = np.array([KobeBryant_Salary, JoeJohnson_Salary, LeBronJames_Salary, CarmeloAnthony_Salary, DwightHoward_Salary, ChrisBosh_Salary, ChrisPaul_Salary, KevinDurant_Salary, DerrickRose_Salary, DwayneWade_Salary])


#Games 
KobeBryant_G = [80,77,82,82,73,82,58,78,6,35]
JoeJohnson_G = [82,57,82,79,76,72,60,72,79,80]
LeBronJames_G = [79,78,75,81,76,79,62,76,77,69]
CarmeloAnthony_G = [80,65,77,66,69,77,55,67,77,40]
DwightHoward_G = [82,82,82,79,82,78,54,76,71,41]
ChrisBosh_G = [70,69,67,77,70,77,57,74,79,44]
ChrisPaul_G = [78,64,80,78,45,80,60,70,62,82]
KevinDurant_G = [35,35,80,74,82,78,66,81,81,27]
DerrickRose_G = [40,40,40,81,78,81,39,0,10,51]
DwayneWade_G = [75,51,51,79,77,76,49,69,54,62]
#Matrix
Games = np.array([KobeBryant_G, JoeJohnson_G, LeBronJames_G, CarmeloAnthony_G, DwightHoward_G, ChrisBosh_G, ChrisPaul_G, KevinDurant_G, DerrickRose_G, DwayneWade_G])


#Field Goals
KobeBryant_FG = [978,813,775,800,716,740,574,738,31,266]
JoeJohnson_FG = [632,536,647,620,635,514,423,445,462,446]
LeBronJames_FG = [875,772,794,789,768,758,621,765,767,624]
CarmeloAnthony_FG = [756,691,728,535,688,684,441,669,743,358]
DwightHoward_FG = [468,526,583,560,510,619,416,470,473,251]
ChrisBosh_FG = [549,543,507,615,600,524,393,485,492,343]
ChrisPaul_FG = [407,381,630,631,314,430,425,412,406,568]
KevinDurant_FG = [306,306,587,661,794,711,643,731,849,238]
DerrickRose_FG = [208,208,208,574,672,711,302,0,58,338]
DwayneWade_FG = [699,472,439,854,719,692,416,569,415,509]
#Matrix
FieldGoals  = np.array([KobeBryant_FG, JoeJohnson_FG, LeBronJames_FG, CarmeloAnthony_FG, DwightHoward_FG, ChrisBosh_FG, ChrisPaul_FG, KevinDurant_FG, DerrickRose_FG, DwayneWade_FG])


print(np.sum(Salary, axis = 0))
print(np.sum(Salary, axis = 1))

print(np.sum(Games, axis = 0))
print(np.sum(Games, axis = 1))

print(np.sum(FieldGoals, axis = 0))
print(np.sum(FieldGoals, axis = 1))

[ 50299635  57248613  98406186 120776420 139835227 144667149 166489555
 189711742 205782921 204790923]
[229306822 166205113 141461033 151622715 140546503 138008113 116051459
  88510296  75445211 130851106]
[701 618 716 776 728 780 560 663 596 531]
[653 739 752 673 727 684 699 639 460 643]
[5878 5248 5898 6639 6416 6383 4654 5284 4696 3941]
[6431 5360 7533 6293 4876 5051 4604 5826 3279 5784]
